### ISSUE TITLE
gRPC gateway forwarding 

### ISSUE THREAD

**Issue by jianmo1997** [Albertoimpl/grpc-samples#1]
Sorry to interrupt 

Our team now has a difficult problem

We try to use spring-cloud-gateway as a transit gateway for gRPC , because we recently saw that spring cloud gateway supports the HTTP/2 protocol,But it is a pity that the following problems occurred when we called

```
reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ HTTP POST "/com.example.grpc.HelloService/hello" [ExceptionHandlingWebHandler]
Stack trace:
```

The request received by grpc server is also http1.x

```
io.netty.handler.codec.http2.Http2Exception: Unexpected HTTP/1.x request: POST /com.example.grpc.HelloService/hello 
```

This is very confusing and annoying. We know that the request is sent out through the filter of `NettyRouterFilter`, and we have also turned on the configuration of `server.http2.endabled:true`

At the same time, we look at your submissions and attempts on gRPC at spring-cloud-gateway. We found here based on relevant clues. We think you have gone further than us in this regard, and hope to hear your suggestions on this issue. , This is very important to us

thank you !

**Comment by Albertoimpl** [comment]
Hey @jianmo1997! Sad to see you are having trouble.
Since this is not in the GA release yet it was not properly documented. However, I am preparing a blog post that will be coming out next week where we detail everything you need in order to get this support working: https://github.com/Albertoimpl/spring-cloud-gateway-grpc
Let me know if this helps!

**Comment by Albertoimpl** [comment]
ICYMI @jianmo1997 https://spring.io/blog/2021/12/08/spring-cloud-gateway-and-grpc
